
import { Product } from '../../types';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Amoxicillin 500mg Capsules',
    category: 'Antibiotics',
    price: 1500,
    supplier: 'Davita Pharma Ltd',
    image: 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?auto=format&fit=crop&q=80&w=800',
    description: 'High-quality Amoxicillin capsules in a box of 10x10 blisters. Essential for bacterial infection treatment.',
    stock: 500,
    rating: 4.8,
    verified: true,
  },
  {
    id: '2',
    name: 'Panadol Extra (Box of 100)',
    category: 'Pain Relief',
    price: 2200,
    supplier: 'Nairobi Medical Supplies',
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&q=80&w=800',
    description: 'Original Panadol Extra for strong pain relief. Bulk pack suitable for pharmacy retail.',
    stock: 1200,
    rating: 4.9,
    verified: true,
  },
  {
    id: '3',
    name: 'Insulin Glargine Injection',
    category: 'Diabetes Care',
    price: 3500,
    supplier: 'MedPlus Kenya',
    image: 'https://images.unsplash.com/photo-1631549916768-4119b2e5f926?auto=format&fit=crop&q=80&w=800',
    description: 'Long-acting insulin for diabetes management. Cold chain storage guaranteed during delivery.',
    stock: 50,
    rating: 4.7,
    verified: true,
  },
  {
    id: '4',
    name: 'Disposable Surgical Masks (50pcs)',
    category: 'Medical Supplies',
    price: 350,
    supplier: 'SafeHealth Distributors',
    image: 'https://images.unsplash.com/photo-1584036561566-b45238f2e121?auto=format&fit=crop&q=80&w=800',
    description: '3-ply medical grade surgical masks. KEBS certified.',
    stock: 5000,
    rating: 4.5,
    verified: true,
  },
  {
    id: '5',
    name: 'Cough Syrup (Paediatric)',
    category: 'Respiratory',
    price: 450,
    supplier: 'Davita Pharma Ltd',
    image: 'https://images.unsplash.com/photo-1512069772995-ec65ed45afd6?auto=format&fit=crop&q=80&w=800',
    description: 'Soothing cough syrup for children. Strawberry flavor.',
    stock: 200,
    rating: 4.6,
    verified: true,
  },
  {
    id: '6',
    name: 'Omeprazole 20mg',
    category: 'Gastrointestinal',
    price: 800,
    supplier: 'Kenya Generics',
    image: 'https://images.unsplash.com/photo-1550572017-edd951aa8f72?auto=format&fit=crop&q=80&w=800',
    description: 'Effective relief for acid reflux and ulcers. Box of 30 tablets.',
    stock: 300,
    rating: 4.2,
    verified: false,
  },
  {
    id: '7',
    name: 'Metformin 500mg',
    category: 'Diabetes Care',
    price: 600,
    supplier: 'HealthFirst Kenya',
    image: 'https://images.unsplash.com/photo-1628771065518-0d82f0263329?auto=format&fit=crop&q=80&w=800',
    description: 'First-line medication for the treatment of type 2 diabetes. Box of 100 tablets.',
    stock: 800,
    rating: 4.9,
    verified: true,
  },
  {
    id: '8',
    name: 'Ibuprofen 400mg',
    category: 'Pain Relief',
    price: 1200,
    supplier: 'Nairobi Medical Supplies',
    image: 'https://images.unsplash.com/photo-1585232375863-1293397f02b1?auto=format&fit=crop&q=80&w=800',
    description: 'Anti-inflammatory pain relief. Suitable for joint pain and headaches.',
    stock: 1500,
    rating: 4.8,
    verified: true,
  },
  {
    id: '9',
    name: 'Sterile Latex Gloves (Box of 100)',
    category: 'Medical Supplies',
    price: 950,
    supplier: 'SafeHealth Distributors',
    image: 'https://images.unsplash.com/photo-1591857177580-dc82b9a454c3?auto=format&fit=crop&q=80&w=800',
    description: 'Powder-free sterile latex gloves. Essential for clinical examinations.',
    stock: 3000,
    rating: 4.7,
    verified: true,
  },
  {
    id: '10',
    name: 'Ceftriaxone 1g Injection',
    category: 'Antibiotics',
    price: 280,
    supplier: 'MedPlus Kenya',
    image: 'https://images.unsplash.com/photo-1579165466741-7f35a4755657?auto=format&fit=crop&q=80&w=800',
    description: 'Broad-spectrum antibiotic injection. Requires prescription verification.',
    stock: 400,
    rating: 4.9,
    verified: true,
  },
  {
    id: '11',
    name: 'Vitamin C 1000mg Effervescent',
    category: 'Respiratory',
    price: 1200,
    supplier: 'Kenya Generics',
    image: 'https://images.unsplash.com/photo-1512069772995-ec65ed45afd6?auto=format&fit=crop&q=80&w=800',
    description: 'Immune boosting effervescent tablets. Orange flavor.',
    stock: 600,
    rating: 4.5,
    verified: false,
  },
  {
    id: '12',
    name: 'First Aid Kit (Professional)',
    category: 'Medical Supplies',
    price: 4500,
    supplier: 'SafeHealth Distributors',
    image: 'https://images.unsplash.com/photo-1603398938378-e54eab446dde?auto=format&fit=crop&q=80&w=800',
    description: 'Complete professional first aid kit compliant with OSHA standards for workplaces.',
    stock: 100,
    rating: 4.9,
    verified: true,
  },
    {
    id: '13',
    name: 'Panadol Extra (Box of 100)',
    category: 'Pain Relief',
    price: 2100,
    supplier: 'Sigs Medical Supplies',
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&q=80&w=800',
    description: 'Original Panadol Extra for strong pain relief. Bulk pack suitable for pharmacy retail.',
    stock: 100,
    rating: 3.9,
    verified: true,
  },
];

export const KENYA_COUNTIES = [
  "Nairobi", "Mombasa", "Kisumu", "Nakuru", "Uasin Gishu", "Machakos", "Kiambu", "Meru", "Nyeri", "Kakamega"
];
